# Generated by Django 4.2.11 on 2024-04-10 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provinces', '0002_province_old_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubMunicipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('old_names', models.CharField(max_length=200, null=True)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provinces.province')),
            ],
        ),
    ]
