# Generated by Django 4.2.11 on 2024-04-10 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipalities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='old_names',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
