# Generated by Django 5.0.4 on 2024-04-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipalities', '0002_municipality_old_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='type',
            field=models.CharField(choices=[('Mun', 'Municipality'), ('City', 'City'), ('SubMun', 'Sub-Municipality'), ('SGU', 'Special Government Unit')], max_length=100, null=True),
        ),
    ]
